version: '3.8'

services:
  angular-app:
    build: .
    ports:
      - "4201:4201"
    volumes:
      - .:/app
      - /app/node_modules # evita sobrescrever os node_modules do container
    environment:
      - CHOKIDAR_USEPOLLING=true # ajuda com hot reload em ambientes Linux/WSL
